export const TAGS = [
  "Explicação Clara",
  "Exemplos Práticos",
  "Confuso",
  "Boa Comunicação",
  "Falta Clareza",
  "Conhecimento Profundo",
  "Superficial",
  "Empatia",
  "Falta Empatia",
  "Aplicação Prática",
  "Teoria Apenas",
  "Boas Dicas Comunicação",
  "Comunicação Fraca",
  "Orientação Carreira",
  "Pouca Orientação",
  "Disponível",
  "Pouca Disponibilidade",
  "Pensamento Crítico",
  "Falta Pensamento Crítico",
  "Inclusivo",
  "Exclusivo",
  "Atualizado",
  "Desatualizado",
  "Resolução Problemas",
  "Dificuldade Resolução",
  "Bom Feedback",
  "Falta Feedback",
  "Boa Interação",
  "Dificuldade Interação",
  "Motivador",
  "Desmotivador",
  "Entusiasmado",
  "Desinteressado",
  "Colaborativo",
  "Individualista",
  "Organizado",
  "Desorganizado",
  "Pontual",
  "Atrasado",
  "Informativo",
  "Pouco Informativo",
  "Inspirador",
  "Desinspirador",
  "Adaptável",
  "Inflexível",
  "Respeitoso",
  "Irrespeitoso",
  "Ético",
  "Antiético",
];
