export const WEBHOOK = {
  CAL_BOOKING_CREATED: "CAL_BOOKING_CREATED",
  CAL_MEETING_ENDED: "CAL_MEETING_ENDED",
  CAL_MEETING_STARTED: "CAL_MEETING_STARTED",
  CAL_BOOKING_CANCELLED: "CAL_BOOKING_CANCELLED",
  STRIPE_PAYMENT_INTENT_SUCCEEDED: "STRIPE_PAYMENT_INTENT_SUCCEEDED",
};
